services:
  backend:
    image: app-backend
    build:
      context: .
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      app-network:
        ipv4_address: ${BACKEND_ADDR}
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_ADDR}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      AES_ENCRYPTION_SECRET: ${AES_KEY}
      JWT_REFRESH-TOKEN-KEY: ${JWT_REFRESH}
      JWT_ACCESS-TOKEN-KEY: ${JWT_ACCESS}

  database:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      app-network:
        ipv4_address: ${DB_ADDR}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge
    enable_ipv6: false
    internal: true
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}/${MASK}

volumes:
  db-data: